### ISSUE TITLE
Error while setting up camera with version 1.5.4

### ISSUE THREAD

**Issue by goodfore** [tchellomello/python-amcrest#131]
Hi All,

Since 1.5.4, I got the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/amcrest/__init__.py", line 33, in __init__
    timeout_protocol=timeout_protocol
TypeError: __init__() got an unexpected keyword argument 'verify'

Using this code:
>>> from amcrest import AmcrestCamera
>>> myCamera = AmcrestCamera(IP, 80, user, pass).camera

Works fine in 1.5.3.

New parameter?

Thanks,
Joe

**Comment by leocencetti** [comment]
Hi,
the problem is in the `__init__()` method of the class **AmcrestCamera()** [src/amcrest/__init__.py] in the `self.camera` object creation:

`self.camera = Http(
            host=host,
            port=port,
            user=user,
            password=password,
            verbose=verbose,
            protocol=protocol,
            **verify=verify,**
            retries_connection=retries_connection,
            timeout_protocol=timeout_protocol
        )`

The argument name `verify` does not match what the class **Http()** [src/amcrest/http.py] expects ` (`ssl_verify`). My guessing is that there has been an oversight in the refactoring of the variable name.
While we wait for a fix, you can change the object creation argument name from `verify=verify` to `ssl_verify=verify`, and everything should work fine.

**Comment by pnbruckner** [comment]
This should be fixed in 1.5.5.
